name: docs

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    name: Prepare Documentation for Deployment

    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Docs
        uses: andstor/jsdoc-action@v1
        with:
          config_file: ./jsdoc.json
          
      - name: Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    name: Deploy Documentation to GitHub Pages
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docs
        id: deployment
        uses: actions/deploy-pages@v4
